#ifndef LIBREMOTESENSING_GLOBAL_H
#define LIBREMOTESENSING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBREMOTESENSING_LIBRARY)
#  define LIBREMOTESENSINGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBREMOTESENSINGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBREMOTESENSING_GLOBAL_H
